scripts/no_sandbox.sh

In the past, courses were installed under the exercises directory of
the mooc-grader, but the directory was then renamed to courses.
`scripts/no_sandbox.sh` has been using the old path when it sets the `PATH` of the process, but this PR fixes that.

Fix the old course directory path used in no_sandbox.sh

---

access/templates/access/accept_general_default.html
access/templates/access/accept_general_form.html
access/templates/access/active_element_default.html
access/templates/access/active_element_feedback.html
access/types/stdasync.py
courses/README.md

Adds view type and templates for active elements. The view type acceptGeneralForm is effectively a combination of acceptPost and acceptFiles and should be able to handle general form submits that include files, text inputs and dropdowns (other input types not tested). The default template for the type currently creates a text input for any other input than file.

Add active elements

---

access/management/commands/pregenerate_exercises.py

This small improvement is especially useful for the run-mooc-grader container.
Do not raise an exception if the given course has no personalized exercises;
the command can then be run with all courses without crashing.
Add an option to only generate new instances if none exist yet.
This allows the run-mooc-grader container to use the command and
still preserve any previously generated and stored instances.

Improve the pregenerate_exercises command

---

access/templates/access/accept_general_default.html
access/templates/access/accept_git_default.html
access/templates/access/accept_post_default.html
access/templates/access/create_form_default.html

Title and code should be self-explanatory. Of course if the previous behaviour was by design, then this is a useless PR :)

add exercise.instructions_file to templates that were missing it

---

.gitignore
courses/README.md
util/personalized.py

This change makes it possible for pregenerating personalized exercises both in local environment powered by course-templates docker/docker-compose setup *and* in production environment.
When the course is developed locally, it is located in mooc-grader file system in courses/default. When the course is deployed to production mooc-grader server, the location is almost certainly different, for instance courses/wsd-2018. Because the paths are different the "cwd" parameter of "generator" in exercise.yml doesn't help, it would need to be rewritten depending on the environment.
My proposal changes the behaviour of **_manage.py pregenerate_exercises <course_key>_** so that the "cmd" of "generator" will be executed from courses/<course_key>, not from the mooc-grader's root path where manage.py …

use course key as cwd for generator cmd by default

---

access/config.py
access/templates/access/graded_form.html
access/types/forms.py
access/views.py

and add a special case for hidden fields in graded_form.html.
Get language from POST if available.
This handles the language mismatch bug in every case that applies to O1,
except for the piazza exercise. Because whether A+ loads the previous submission
is decided by the course material and not grader, it is almost impossible to
fix the bug in general.

Add lang field to GradedForm

---

access/views.py
courses/README.md

Previously, many course settings were not included in the
aplus-json, such head_urls, enrollment_start, or view_content_to.
This commit adds many of the missing settings.

Add course settings to the aplus-json

---

access/types/forms.py

In questionnaires freetext-questions ignorews-option previously only cleared spaces, but didn't do so to tabs or newlines.

Fix ignorews option to ignore all whitespace, not just spaces

---

access/types/forms.py
courses/README.md

Add `show_correct_once` option to exercise configuration to show model answer
after the last submission.

Don't show correct answer by default in the questionnaires

---

access/templates/access/graded_form.html
access/types/forms.py

Use question marks in the model answer shown after the last submission to indicate neutral choises, that could have been chosen or not.

Neutral answers in the model solution

---

access/templates/access/_error_summary.html
access/templates/access/create_form_default.html
access/templates/access/graded_form.html
access/types/forms.py
locale/fi/LC_MESSAGES/django.po

~~Preferably not to be merged before: https://github.com/apluslms/mooc-grader/pull/76~~
Related to the changes in: https://github.com/apluslms/a-plus/pull/637
Fixes: https://github.com/apluslms/a-plus/issues/592 
Related also to solving: https://github.com/apluslms/a-plus/issues/593 and https://github.com/apluslms/a-plus/issues/591 
**1. Implements auto_id for questionnaire fields.**
- The auto_id contains a random string as a separating factor for different fields. 
- This has been done for the cases where there are multiple questionnaires on the same page, this separates the fields of those questionnaires for better accessibility, and also makes handling errors on the front-end easier. 
**2. Removes the required-attr addition from questionnaire widgets** 
- Now that Django has been …

Questionnaire feedback summary - changes in mooc-grader

---

access/templates/access/graded_form.html
access/templates/access/graded_form_feedback.html
access/types/forms.py
access/types/stdsync.py
locale/fi/LC_MESSAGES/django.po

Fixes: https://github.com/apluslms/mooc-grader/issues/55 
Neutral options of checkbox-type questions have been added to the model answer in questionnaire. Previously they only showed briefly at the moment when the student reached maximum amount of submissions if the “reveal-model-at-max-submissions" was set to true. 
At the same time, the role of these two different model answers have been cleared up a bit and pushed towards the other [general exercise configuration](https://github.com/apluslms/mooc-grader/tree/master/courses#accesstypesstdsynccreateform), by renaming the form attributes for the model answers.
The only visible change to appearance, is the indication of neutral answers and hiding the option-related hints, when checking the model answer:
Has been tested with: 
1. Normal …

Neutral options

---

courses/README.md

The `model_files` configuration exists in the source code, but
there is no mention of that specific configuration value in the
courses/README.md file. Therefore, a brief description has been
added

Add description of the `model_files` to the courses/README.md

---

access/templates/access/_error_summary.html

Changes the style of the items in the error summary,
adds emphasis on the field label, and presents the errors
as ul-element, instead of individual p-elements.
Related to the changes: https://github.com/apluslms/a-plus/pull/658
And in: https://github.com/apluslms/a-plus-design-system/pull/9
Testing of the outlook has been done in: https://github.com/apluslms/a-plus/pull/658

Change style of list-items in error summary

---

access/types/stdasync.py
courses/README.md

Update the way the container options are given to the k8s script - now all `container` fields are given, which allows adding / changing the k8s environment options more freely with less hassle. Also updated exercise documentation, replacing the deprecated `actions` field with the more up-to-date `container` field and its options.
Manually tested. Updated k8s-run script on minus.cs.
Yep.

Update format of container options given to the creation script & update docs

---

access/templates/access/graded_form.html
access/types/forms.py

The status-text "Correct!" and the points badges (0/0 for all questions, regardless of the answer) were shown for enrollment questionnaires too. This removes them as unnecessary feedback. The green alert of "you got 0/0 points for this questionnaire" was already removed in an earlier pull request. 
**Before changes** 
**After changes** 
If there is an required answer missing from the questionnaire, that is displayed now also better due to the earlier pull requests:
Doesn't require updates.

Disable points and feedback from enrollment questionnaire

---

access/types/stdasync.py
grader/settings.py
requirements.txt
util/personalized.py

As mentioned in #58 the personal directory is not longer used.
Fixes #89
I tested the personalised exercises of the Aplus manual and they worked as expected.
...
*Clean up your git commit history before submitting the pull request!*

Remove personal directory feature from personalised exercises

---

access/templates/access/graded_form.html

**What?**
Remove duplicate nested "label" element from questionnaire forms.
**Why?**
Only one is necessary.
**How?**
When field.label_tag is used in the template, don't wrap it in a "label" element.
Fixes #97
**Remember to add or update unit tests for new features and changes.**
* How to [test your changes in A-plus](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations)
* How to [test accessibility](https://wiki.aalto.fi/display/EDIT/How+to+check+the+accessibility+of+pull+requests)
Opened a questionnaire page and used Firefox's inspector to verify that there is now only one "label" element.
**Think of what is affected by these changes and could become broken**
*Clean up your git commit …

Remove duplicate label HTML tag. Fixes #97

---

README.md
doc/gitmanager-crontab
gitmanager/cron.sh

**What?**
Removed a sudo call from gitmanager's `cron.sh` script and updated the documentation accordingly.
**Why?**
The sudo call is not required in the current non-chroot-sandbox deployment, and was additionally interfering with running gitmanager in a production container.
Tested running `cron.sh` as the `grader` user on the minus.cs test server.

Non sudo gitmanager cron

---

grader/settings.py

Added an environmental-variable enabled option to disable parsing environment variables starting with `GRADER_` or `DJANGO_` as settings.
**Why?**
The old non-checking version could accidentally parse undesired environment variables as settings. These variables could be set e.g. by Kubernetes, if pods / service names started with `grader`, and there was no way of overriding in local_settings.py, as the code is executed in settings.py in any case.
This was especially meaningful in gitmanager's functionality, as some of the variables set couldn't be parsed in JSON, throwing errors. When running gitmanager's read_static_dir command, the errors would be appended to the directory name output by the command, garbling the actual result.
**How?**
Setting the DISABLE_LOAD_ENVIRONMENT_SETTINGS …

Conditionally disable loading settings from environment variables

---

grader/settings.py

**What?**
Change the recently-changed environment variable based settings loading again to not binarily enable or disable loading settings from environment variables, but instead define custom prefix to load settings from.
**Why?**
Loading environment variables can still prove useful as long as it's done in a controlled manner.
**How?**
Load prefix from ENV_SETTINGS_PREFIX, then load settings from env variables with said prefix.

Change environment variable setting loading schema

---

.dockerignore
access/converters.py
access/urls.py
access/views.py
grader/settings.py
requirements.txt
util/auth.py
util/log.py
util/login_required.py

**What?**
Update aplus-auth to 0.2.0, add permission checks to views, add logging, and fix custom template caching.
**Why?**
Shortens JWT lengths, and increases security.
Security logging was required.
Templates wouldn't be reloaded after they were changed.
**How?**
Respond with 403 if the course key is an integer (i.e. it is the remote id) and the user has no access.
Logging on endpoints where there could be an effect to the course.
Remove caching of courses' custom templates.

Update aplus-auth to 0.2.0, add permission checks to views, add logging, fix custom template caching

---

access/config.py
access/views.py

**What?**
Allow the language(s) to be specified in either lang or language fields. There was also a bug if the 'language' contains a string but the DEFAULT_LANG has probably masked that in the past.
**Why?**
The field name was changed in a-plus-rst-tools to match the field name in A+.
**How?**
Check both language and lang for if the field is a list of languages. Also, saves the language list in the 'lang' field instead of just the default language, so the hack can be removed from aplus-json. The 'lang' field of the course entry doesn't seem to be used anywhere anyway (course root 'lang' is used though).
Fixes #132
Checked that O1 course loads properly. It is technically possible that this breaks something if I missed any 'lang' field usages but I'm …

Fix lang/language field handling

---

access/types/stdasync.py
courses/README.md
util/export.py

**What?**
Enables LTI user attributes (real student id and name) for a selected mooc-grader execise if the mooc-grader server has an LTI configuration at A-plus.
**Why?**
A use case in "Applications for computing" and "Mechatronic Machine Design" requires to check a certificate from Matlab onramp with students real name. They hope to use this starting from January and using existing support in A-plus is the only way I can see it done in this timeframe.
**How?**
1. Supports LTI configuration in mooc-grader exercise which is handled in the A-plus "fetch settings" (as previously used for Rubyric exercises). If a matching LTI-service for the mooc-grader server is configured in the A-plus it will append LTI user attributes for requests to that specific mooc-grader exercise. No code changes in …

Enable LTI parameters for grading

---

access/templates/access/async_accepted.html
access/templates/access/exercise_head.html
access/types/stdasync.py
courses/README.md
locale/en/LC_MESSAGES/django.po
locale/fi/LC_MESSAGES/django.po

They seem to be relics from a time the system used celery instead of docker.
The change basically replaces the `wait` and `queue < 3` statements with True, and omits any unreachable code given that.
I only did very basic test of checking that I can still submit things because of how simple the change is.

Remove and clean up old queue and wait variables

---

access/views.py
requirements.txt
util/misc.py

**What?**
Remove features deprecated and removed in Django version 4.0, 4.1, and 4.2.
**Why?**
Django 4.2 (LTS) was released in April 2023. Django v3.2 reaches end of life in April 2024.
**How?**
I went through the release notes for Django 4.0, 4.1 and 4.2 and checked which deprecated and removed features appear in the codebase and removed/edited them.
Fixes #147
Tested for no obvious errors.

Upgrade from Django 3.2 to 4.2

---

access/templatetags/access.py
access/types/forms.py
locale/en/LC_MESSAGES/django.po
locale/fi/LC_MESSAGES/django.po

**What?**
Add an additional feedback note on pick-anys when partial-points option is not used and the answer is incorrect.
**Why?**
Students sometimes assume that zero points means “nothing is correct”; moreover, they sometimes expect to get partial credit.
Fixes #150
Tested that the new feedback note only shows in pick-any questions without partial-points option when the answer is incorrect.

Improve generic feedback on pick-any questions

---

access/views.py
locale/en/LC_MESSAGES/django.po
locale/fi/LC_MESSAGES/django.po

**What?**
The grading-base sends an additional ``feedback_size_error`` field to the MOOC-Grader when the feedback for a submission is too large. This is now used to determine if a warning about long feedback length should be displayed to a student.
**Why?**
If an assignment grader prints massive amounts of text to the feedback, saving it to A+ fails. This happens especially when the student's own print outputs are included in the feedback and the student prints lots of data in a loop. In these cases, A+ should show useful feedback to the student that warns about the massive feedback and advises them to avoid printing extra output.
Fixes #146
Tested that submissions with very large feedback now display an informative error message in A+ instead of getting …

Display a warning when submission feedback is too large

---

access/types/forms.py
access/types/stdsync.py
util/export.py

**What?**
Add support for `placeholder` value in the FreeText `:extra:` option.
**How to use?**
```
.. freetext:: 5
:height: 2
:extra: validationMessage=Please check your answer is correctly formatted;placeholder=This text is shown as a placeholder
```
Fixes apluslms/a-plus#1143
Tested that the placeholder text is shown correctly with multiple languages in both normal questionnaires and MOOC-Jutut questionnaires.

Support placeholder text in questionnaire FreeText fields
